# Kafka configuration
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    embedded:
      enabled: ${KAFKA_EMBEDDED:true}  # Set to false to use external Kafka
      topics: solver-requests, solver-responses
    consumer:
      group-id: solver-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    solver:
      request: solver-requests
      response: solver-responses

solver:
  mode: remote-kafka
