spring:
  application:
    name: artifactid

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        schema-generation:
          scripts:
            action: create
            create-target: target/schema.sql

storage:
  type: local

