solution status: optimal solution found
objective value:                                   88
Edge#1$Shin Gimel#0                                 1 	(obj:1)
Edge#1$Shin Gimel#1                                 1 	(obj:1)
Edge#1$Shin Gimel#2                                 1 	(obj:1)
Edge#1$Shin Gimel#3                                 1 	(obj:1)
Edge#1$Shin Gimel#4                                 1 	(obj:1)
Edge#1$Shin Gimel#5                                 1 	(obj:1)
Edge#1$Shin Gimel#6                                 1 	(obj:1)
Edge#1$Shin Gimel#7                                 1 	(obj:1)
Edge#1$Shin Gimel#8                                 1 	(obj:1)
Edge#1$Shin Gimel#9                                 1 	(obj:1)
Edge#1$Shin Gimel#10                                1 	(obj:1)
Edge#2$Siyur#0                                      1 	(obj:1)
Edge#2$Siyur#1                                      1 	(obj:1)
Edge#2$Siyur#2                                      1 	(obj:1)
Edge#2$Siyur#3                                      1 	(obj:1)
Edge#2$Siyur#4                                      1 	(obj:1)
Edge#2$Siyur#5                                      1 	(obj:1)
Edge#2$Siyur#6                                      1 	(obj:1)
Edge#2$Siyur#7                                      1 	(obj:1)
Edge#2$Siyur#8                                      1 	(obj:1)
Edge#2$Siyur#9                                      1 	(obj:1)
Edge#2$Siyur#10                                     1 	(obj:1)
Edge#3$Fillbox#0                                    1 	(obj:1)
Edge#3$Fillbox#1                                    1 	(obj:1)
Edge#3$Fillbox#2                                    1 	(obj:1)
Edge#3$Fillbox#3                                    1 	(obj:1)
Edge#3$Fillbox#4                                    1 	(obj:1)
Edge#3$Fillbox#5                                    1 	(obj:1)
Edge#3$Fillbox#6                                    1 	(obj:1)
Edge#3$Fillbox#7                                    1 	(obj:1)
Edge#3$Fillbox#8                                    1 	(obj:1)
Edge#3$Fillbox#9                                    1 	(obj:1)
Edge#3$Fillbox#10                                   1 	(obj:1)
Edge#4$North#0                                      1 	(obj:1)
Edge#4$North#1                                      1 	(obj:1)
Edge#4$North#2                                      1 	(obj:1)
Edge#4$North#3                                      1 	(obj:1)
Edge#4$North#4                                      1 	(obj:1)
Edge#4$North#5                                      1 	(obj:1)
Edge#4$North#6                                      1 	(obj:1)
Edge#4$North#7                                      1 	(obj:1)
Edge#4$North#8                                      1 	(obj:1)
Edge#4$North#9                                      1 	(obj:1)
Edge#4$North#10                                     1 	(obj:1)
Edge#5$West#0                                       1 	(obj:1)
Edge#5$West#1                                       1 	(obj:1)
Edge#5$West#2                                       1 	(obj:1)
Edge#5$West#3                                       1 	(obj:1)
Edge#5$West#4                                       1 	(obj:1)
Edge#5$West#5                                       1 	(obj:1)
Edge#5$West#6                                       1 	(obj:1)
Edge#5$West#7                                       1 	(obj:1)
Edge#5$West#8                                       1 	(obj:1)
Edge#5$West#9                                       1 	(obj:1)
Edge#5$West#10                                      1 	(obj:1)
Edge#6$South#0                                      1 	(obj:1)
Edge#6$South#1                                      1 	(obj:1)
Edge#6$South#2                                      1 	(obj:1)
Edge#6$South#3                                      1 	(obj:1)
Edge#6$South#4                                      1 	(obj:1)
Edge#6$South#5                                      1 	(obj:1)
Edge#6$South#6                                      1 	(obj:1)
Edge#6$South#7                                      1 	(obj:1)
Edge#6$South#8                                      1 	(obj:1)
Edge#6$South#9                                      1 	(obj:1)
Edge#6$South#10                                     1 	(obj:1)
Edge#7$East#0                                       1 	(obj:1)
Edge#7$East#1                                       1 	(obj:1)
Edge#7$East#2                                       1 	(obj:1)
Edge#7$East#3                                       1 	(obj:1)
Edge#7$East#4                                       1 	(obj:1)
Edge#7$East#5                                       1 	(obj:1)
Edge#7$East#6                                       1 	(obj:1)
Edge#7$East#7                                       1 	(obj:1)
Edge#7$East#8                                       1 	(obj:1)
Edge#7$East#9                                       1 	(obj:1)
Edge#7$East#10                                      1 	(obj:1)
Edge#8$Hamal#0                                      1 	(obj:1)
Edge#8$Hamal#1                                      1 	(obj:1)
Edge#8$Hamal#2                                      1 	(obj:1)
Edge#8$Hamal#3                                      1 	(obj:1)
Edge#8$Hamal#4                                      1 	(obj:1)
Edge#8$Hamal#5                                      1 	(obj:1)
Edge#8$Hamal#6                                      1 	(obj:1)
Edge#8$Hamal#7                                      1 	(obj:1)
Edge#8$Hamal#8                                      1 	(obj:1)
Edge#8$Hamal#9                                      1 	(obj:1)
Edge#8$Hamal#10                                     1 	(obj:1)
