services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   depends_on:
  #     - zookeeper

  app:
    image: maxbr1/plan-a-dev
    volumes:
      - .:/Plan-A
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - SPRING_PROFILES_ACTIVE=H2,securityAndGateway,kafkaSolver
      - KEYCLOAK_ISSUER_URI=http://localhost:8080/realms/plan-a
      - KEYCLOAK_JWK_SET_URI=http://localhost:8080/realms/plan-a/protocol/openid-connect/certs
    ports:
      - "4000:4000"
    working_dir: /Plan-A
    stdin_open: true
    tty: true

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://localhost:8080
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/plan-a-dev-realm.json
    ports:
      - "8080:8080"
    volumes:
      - ./realm-config/dev:/opt/keycloak/data/import