FROM quay.io/keycloak/keycloak:24.0.1

# Copy the realm configuration
COPY ./realm-config/prod/plan-a-prod-realm.json /opt/keycloak/data/import/

# Set environment variables
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin123
ENV KC_HOSTNAME_URL=http://localhost:8080
ENV KC_HOSTNAME_ADMIN_URL=http://localhost:8080

# Start Keycloak with realm import
CMD ["start-dev", "--import-realm"] 